"""
Curated replacement titles per channel (Jun/2026), generated from each
channel's SOP title formula + proven top-performers, then enriched with REAL
Google Ads search volume via DataForSEO. Loaded by /api/admin/refresh-titles.

Format: { project_name: [ (title, pillar, priority, search_volume), ... ] }
priority: "ALTA" | "MEDIA"; search_volume = monthly searches of the main keyword.
Sorted by search_volume desc. Matching is by exact project name.
"""

NEW_TITLES: dict[str, list[tuple[str, str, str, int]]] = {
    "POV ATUALIZADO 2": [
        ("Your Life as Every Rank of a Cartel Sicario", "Underworld Ranks", "ALTA", 301000),
        ("POV: You're a Sicario Who Wants Out - But the Cartel Never Lets You Leave", "Underworld Ranks", "ALTA", 301000),
        ("Your Life as Every Name on the FBI Most Wanted List", "Shadow Protocol", "ALTA", 165000),
        ("Your Life as Every Rank in a Mexican Cartel", "Underworld Ranks", "ALTA", 110000),
        ("Your Life as Every Rank in the Yakuza", "Underworld Ranks", "ALTA", 90500),
        ("POV: You Faked Being a Navy SEAL for 20 Years — Until a Real One Showed Up", "Ghost Lives", "MEDIA", 90500),
        ("Your Life as Every Rank in the Italian Mafia", "Underworld Ranks", "ALTA", 74000),
        ("POV: You're a Hitman Who Just Got a Contract on Yourself", "Underworld Ranks", "MEDIA", 60500),
        ("POV: You Run a $2 Billion Ponzi Scheme and It Just Collapsed Overnight", "Dark Fortune", "MEDIA", 60500),
        ("Your Life as Every Rank of a CIA Black Ops Agent", "Shadow Protocol", "ALTA", 27100),
        ("Your Life at Every Level of Witness Protection", "Ghost Lives", "ALTA", 12100),
        ("Your Life as Every Level of an Undercover Cartel Informant", "Underworld Ranks", "ALTA", 0),
        ("Your Life at Every Stage of Faking Your Own Death", "Ghost Lives", "ALTA", 0),
        ("Your Life as Every Level of a Prison Drug Empire", "Broken Badge", "ALTA", 0),
        ("Your Life as Every Rank of an Elite Black-Site Interrogator", "Shadow Protocol", "ALTA", 0),
        ("Your Life at Every Level of an International Manhunt", "Shadow Protocol", "ALTA", 0),
        ("POV: You're the CIA's Only Asset Left Behind Enemy Lines", "Shadow Protocol", "MEDIA", 0),
        ("POV: You're the Accountant Who Knows Where the Cartel Buried Everything", "Underworld Ranks", "MEDIA", 0),
        ("POV: You Win $500M and the Lottery Board Wants You Erased", "Dark Fortune", "MEDIA", 0),
        ("POV: You're a Federal Witness and the Marshals Stopped Answering", "Ghost Lives", "MEDIA", 0),
        ("POV: You're the Cartel's Surgeon and the Boss Is on Your Table", "Underworld Ranks", "MEDIA", 0),
        ("POV: You're a Sleeper Agent Who Forgot Which Side Activated You", "Shadow Protocol", "MEDIA", 0),
        ("POV: You Run the Black Site That Officially Doesn't Exist", "Shadow Protocol", "MEDIA", 0),
        ("POV: You're the Only Honest Cop in a City the Cartel Owns", "Broken Badge", "MEDIA", 0),
    ],
    "Ghibli Cozy Life": [
        ("Rain Sounds for Sleeping: A Cozy Cabin Night Cooking Ramen in the Storm | Studio Ghibli ASMR", "Raindrop Hearth", "ALTA", 201000),
        ("A Cottagecore Autumn: Baking Bread & Foraging Mushrooms in the Forest | Studio Ghibli ASMR", "Harvest Whisper", "ALTA", 201000),
        ("The Sound of Rain on an Old Tin Roof: Slow-Cooking Ramen by Candlelight | Ghibli-Style ASMR", "Raindrop Hearth", "ALTA", 60500),
        ("A Blizzard Outside, a Fire Inside: Baking Cinnamon Bread in a Mountain Cabin | Ghibli-Style ASMR", "Raindrop Hearth", "ALTA", 60500),
        ("First Snow of the Year: A Quiet Night of Hot Cocoa & Apple Pie | Ghibli Cozy Life", "Raindrop Hearth", "ALTA", 60500),
        ("Trapped by a Thunderstorm in a Lighthouse: Warm Clam Chowder & Candlelight | Ghibli-Style ASMR", "Raindrop Hearth", "ALTA", 60500),
        ("Midnight Snow at a Hidden Hot Spring: Warm Sake & Steaming Dumplings | Ghibli-Style ASMR", "Raindrop Hearth", "ALTA", 60500),
        ("Going Back to Grandma's House: Making the Soup I Never Forgot | Ghibli Cozy Life", "Grandma's Seasons", "ALTA", 60500),
        ("The Last Autumn We Spent Together: Picking Persimmons & Making Jam | Ghibli Cozy Life", "Grandma's Seasons", "ALTA", 60500),
        ("A Letter Found in Dad's Old Recipe Book: Cooking His Curry on a Rainy Day | Ghibli-Style Video", "Grandma's Seasons", "ALTA", 60500),
        ("Winters at the Wood Stove: Grandma's Sweet Potato Soup, Just Like Before | Ghibli Cozy Life", "Grandma's Seasons", "ALTA", 60500),
        ("The Christmas She Brought Us All Home: Baking Cookies One Last Time | Ghibli Cozy Life", "Grandma's Seasons", "MEDIA", 60500),
        ("We Built a Bamboo Kitchen From Nothing: Our First Meal in the Forest | Ghibli-Style ASMR", "Wilderness Kitchen", "MEDIA", 60500),
        ("Cooking Inside an Abandoned Plane on a Cliff: Noodle Soup & Mountain Wind | Ghibli-Style ASMR", "Wilderness Kitchen", "MEDIA", 60500),
        ("Snowed In on a Frozen Lake: Ice Fishing & Cooking the Catch in a Warm Tent | Ghibli-Style ASMR", "Wilderness Kitchen", "MEDIA", 60500),
        ("A Night in a Desert Cave: Clay-Oven Flatbread & Mint Tea Under the Stars | Ghibli-Style ASMR", "Wilderness Kitchen", "MEDIA", 60500),
        ("A Quiet Week Living Alone: Slow Mornings & Cooking for One | Ghibli Cozy Life", "Solitude Rituals", "MEDIA", 60500),
        ("Moving to the Countryside: My First Morning in a Simpler Life | Ghibli Cozy Life", "Solitude Rituals", "MEDIA", 60500),
        ("A Rainy Evening Alone With My Cat: Making Onigiri by Candlelight | Ghibli Cozy Life", "Solitude Rituals", "MEDIA", 60500),
        ("Reorganizing My Tiny Kitchen on a Rainy Sunday: Comfort Pasta for One | Ghibli Cozy Life", "Solitude Rituals", "MEDIA", 60500),
    ],
    "ANACRON": [
        ("El UNICO Hombre que Engano a la CIA y al Cartel al Mismo Tiempo", "Espionaje y Agentes Encubiertos", "ALTA", 74000),
        ("La Nina de 12 Anos que Hundio a un Cartel Entero", "Crimen Organizado y Carteles", "ALTA", 74000),
        ("Como un Agente Solitario Infiltro 3 Carteles en 5 Anos", "Espionaje y Agentes Encubiertos", "ALTA", 74000),
        ("Los 7 Tuneles del Cartel que la DEA Nunca Pudo Cerrar", "Crimen Organizado y Carteles", "ALTA", 74000),
        ("El Narco que Traiciono a su Propio Cartel y Vivio para Contarlo", "Crimen Organizado y Carteles", "ALTA", 74000),
        ("El UNICO Preso que Escapo del Campo 14 de Corea del Norte", "Geopolitica y Regimenes Oscuros", "ALTA", 60500),
        ("Como Escapo el Diplomatico que Sabia Demasiado de Corea del Norte", "Geopolitica y Regimenes Oscuros", "MEDIA", 60500),
        ("Como un Narco Construyo un Imperio que la DEA No Pudo Tocar", "Crimen Organizado y Carteles", "MEDIA", 33100),
        ("El UNICO Hacker que el FBI JAMAS Logro Identificar", "Cibercrimen y Hackers", "ALTA", 27100),
        ("La UNICA Mujer que Salio Viva de la Mafia Rusa", "Espionaje y Agentes Encubiertos", "ALTA", 8100),
        ("El Cartero que Destruyo a la Mafia Mas Poderosa de Italia", "Crimen Organizado y Carteles", "ALTA", 8100),
        ("El Contador que Derribo al Capo que Ningun Ejercito Pudo Tocar", "Crimen Organizado y Carteles", "ALTA", 8100),
        ("Minuto a Minuto: La Fuga de Prision Mas Imposible de la Historia", "Crimen Organizado y Carteles", "MEDIA", 170),
        ("El Mendigo que Sabia el Secreto que Mataria a un Presidente", "Asesinatos Politicos e Historia Sombria", "MEDIA", 0),
        ("Como la DEA Perdio 2,000 Millones en una Sola Noche", "Crimen Organizado y Carteles", "MEDIA", 0),
        ("Como un Adolescente Hackeo al Banco Mas Seguro del Mundo", "Cibercrimen y Hackers", "MEDIA", 0),
        ("700 Dias Infiltrado: El Agente que se Convirtio en Mafioso", "Espionaje y Agentes Encubiertos", "ALTA", 0),
        ("Las 5 Ciudades Sovieticas que el Mundo Decidio Olvidar", "Geopolitica y Regimenes Oscuros", "MEDIA", 0),
    ],
    "POV RUDY": [
        ("Your life as Genghis Khan (The Empire Years)", "POV Historical Figures & Empires", "ALTA", 301000),
        ("The Most Extreme Punishments Genghis Khan Ever Ordered", "POV Historical Figures & Empires", "ALTA", 301000),
        ("The Worst Things That Happened Inside the Roman Colosseum", "POV Historical Figures & Empires", "MEDIA", 301000),
        ("The entire story of Elden Ring, i guess", "POV Dark Sci-Fi / Gaming Lore", "ALTA", 301000),
        ("Your life as a Necron Lord (Warhammer 40k)", "POV Dark Sci-Fi / Gaming Lore", "ALTA", 201000),
        ("Your life as the Last Samurai of a Dead Clan", "POV Historical Figures & Empires", "MEDIA", 165000),
        ("Your life as Every Mexican Cartel Rank", "POV Criminal Underworld / Factions", "ALTA", 110000),
        ("The entire story of the Roman Empire, i guess", "POV Historical Figures & Empires", "ALTA", 110000),
        ("What It's Like to be Every MS-13 Rank", "POV Criminal Underworld / Factions", "ALTA", 90500),
        ("Your life as Miyamoto Musashi's Last Student", "POV Historical Figures & Empires", "ALTA", 74000),
        ("The entire story of Dark Souls, i guess", "POV Dark Sci-Fi / Gaming Lore", "ALTA", 74000),
        ("Your life as a Space Marine Who Survived His First War", "POV Dark Sci-Fi / Gaming Lore", "ALTA", 49500),
        ("What It's Like to be Every Rank of a Warhammer Space Marine", "POV Dark Sci-Fi / Gaming Lore", "ALTA", 49500),
        ("Your life as a Roman Gladiator, i guess", "POV Historical Figures & Empires", "ALTA", 12100),
        ("Your life as a Viking Raider in His Final Winter", "POV Historical Figures & Empires", "ALTA", 1300),
        ("The Most Epic Last Stands in History", "POV Historical Figures & Empires", "ALTA", 0),
        ("The Most Disturbing Ways Empires Collapsed in History", "POV Historical Figures & Empires", "MEDIA", 0),
        ("The Craziest Prison Escapes in History, i guess", "POV Criminal Underworld / Factions", "MEDIA", 0),
        ("The entire story of the Mongol Empire, i guess", "POV Historical Figures & Empires", "MEDIA", 0),
        ("The entire story of Rome's Fall, i guess", "POV Historical Figures & Empires", "MEDIA", 0),
        ("What It's Like to be Every Rank in a Roman Legion", "POV Historical Figures & Empires", "MEDIA", 0),
    ],
    "Sacred Lessons on Wealth": [
        ("El Patron le Dejo un Reloj \"Inutil\" al Jardinero... y Cambio el Destino de su Familia 🤑", "Ancestral Wealth Parables", "ALTA", 165000),
        ("Los 5 LUGARES Donde NUNCA Debes Guardar Tu DINERO — Alejan la Abundancia", "Sacred Laws of Prosperity", "ALTA", 165000),
        ("Los 3 COLORES PROHIBIDOS en tu Casa que EXPULSAN el Dinero 💰", "Sacred Laws of Prosperity", "ALTA", 165000),
        ("Por Que el Dinero SIEMPRE te Abandona Antes del Dia 15 — La Leccion que Sana esa Herida", "Sacred Money Healing", "ALTA", 165000),
        ("El Dia que Dejo de Pedir Perdon por Querer Tener Dinero... y TODO Cambio 💔", "Sacred Money Healing", "MEDIA", 165000),
        ("Si Sientes que NO Mereces Tener Dinero, Este Video Sana Esa Herida que Cargas", "Sacred Money Healing", "MEDIA", 165000),
        ("La Mujer que Limpio Casas 35 Anos y Murio con MAS Dinero que sus Patrones 🤑", "Working Class Spiritual Wealth", "ALTA", 165000),
        ("El Secreto que una Abuela de 74 Anos Guardo en su Biblia Durante 30 Anos de Abundancia 💰", "Ancestral Wealth Parables", "ALTA", 12100),
        ("El Ritual del Primer Dia del Mes que los Abuelos Hacian para Atraer Abundancia", "Sacred Laws of Prosperity", "MEDIA", 12100),
        ("Las 7 PALABRAS que las Personas POBRES Repiten Sin Saber que Espantan la Riqueza", "Sacred Laws of Prosperity", "ALTA", 8100),
        ("Su Jefe le Pago con una Casa \"Vieja\"... Nunca Imagino lo que Habia en el Sotano 🥺", "Ancestral Wealth Parables", "ALTA", 0),
        ("La Rica le Regalo una Biblia \"Vieja\" a su Sirvienta... Sin Saber lo que Guardaba Dentro 💰", "Ancestral Wealth Parables", "ALTA", 0),
        ("La Anciana \"Pobre\" Vendio su Ultima Gallina... Lo que Recibio Despues lo Cambio Todo 💔", "Ancestral Wealth Parables", "ALTA", 0),
        ("60 ANOS y SIN AHORROS: La REGLA de los 7 Dias que lo Cambio TODO", "Dignified Aging & Abundance", "ALTA", 0),
        ("La Verdad DOLOROSA que Nadie te Dice de Por Que las Personas Buenas Viven Pobres 🥺", "Sacred Money Healing", "ALTA", 0),
        ("Una Anciana le Dijo a su Nieta 5 Palabras... y Cambio su Destino Financiero Para Siempre", "Ancestral Wealth Parables", "MEDIA", 0),
    ],
}
